@startuml

abstract GraphicElement <<abstract>> {
  - int x
  - int y
  
  - int movementX
  - int movementY
  - int movementSpeed
  
  - Image element
  - int widthElement
  - int heightElement
  
  - boolean isVisible
  ----
  + {abstract} void load(String directory)
  + {abstract} void update()
  + Rectangle getColision()
  ..getters and setters..
}

class Blast {
  + Blast(int x, int y, String elementDirectory)
}

class Enemy {
  - int points
  --
  + Enemy(int x, int y, String elementDirectory)
  ..getters and setters..
}

class Asteroid {
  + Asteroid(int x, int y, String elementDirectory)
}

class Player {
  - int lives
  - int points
  --
  + Player(String elementDirectory)
  + void shoot()
  + void move(KeyEvent key)
  + void stop(KeyEvent key)
  ..getters and setters..
}

abstract Commands <<abstract>> {
  - boolean upCommand
  - boolean downCommand
  - boolean leftCommand
  - boolean rightCommand

  - boolean blastCommand
  - boolean superBlastCommand
  ----
  ..getters and setters..
}

abstract Stage <<abstract>> {
  # Image background
  # Timer timer
  # boolean inGame
  # boolean gameOver
  --
  + Stage()
  + {abstract} void startBackgroundGEs()
  + {abstract} void startEnemies()
  + {abstract} void verifyColisions()
  + {abstract} void paint(Graphics g)
  + {abstract} void keyTyped(KeyEvent e)
  + {abstract} void keyPressed(KeyEvent e)
  + {abstract} void keyReleased(KeyEvent e)
  + {abstract} void actionPerformed(ActionEvent e)
}

GraphicElement <|-- Asteroid :extends
GraphicElement <|--- Player :extends
GraphicElement <|- Blast :extends
GraphicElement <|- Enemy :extends

Player "1" *--> "*" Blast
Player "1" *--> "1" Commands

Stage "1" *--> "1" Player
Stage "1" *---> "*" Enemy
Stage "1" *---> "*" Asteroid

interface KeyListener <<interface>> {
  + void keyTyped(KeyEvent e)
  + void keyPressed(KeyEvent e)
  + void keyReleased(KeyEvent e)
}

interface ActionListener <<interface>> {
  + void actionPerformed(ActionEvent e)
}

class JPanel {
  + void paint(Graphics g)
}

Stage ....|> KeyListener :implements
Stage --|> JPanel :extends
Stage .|> ActionListener :implements

@enduml
